repos:
-   repo: https://github.com/ambv/black
    rev: 21.4b2
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8/
    rev: 3.9.1
    hooks:
    - id: flake8
      args: ['--ignore=W503,E501']

